name: trigger

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check for recent changes in lucide icons repo
      - run: exit $(curl -s https://api.github.com/repos/lucide-icons/lucide/commits/main | jq -r "((now - (.commit.author.date | fromdateiso8601) )  / (60*60*24)  | trunc)")
